include Bezier.Make (V3)

let translate p t u = V3.translate p (t u)
let xtrans x t u = V3.xtrans x (t u)
let ytrans y t u = V3.ytrans y (t u)
let ztrans z t u = V3.ztrans z (t u)
let rotate ?about r t u = V3.rotate ?about r (t u)
let xrot ?about r t u = (V3.xrot ?about r) (t u)
let yrot ?about r t u = (V3.yrot ?about r) (t u)
let zrot ?about r t u = (V3.zrot ?about r) (t u)
let affine m t u = Affine3.transform m (t u)
let quaternion ?about q t u = Quaternion.transform ?about q (t u)
let axis_rotate ?about ax a = quaternion ?about (Quaternion.make ax a)
let scale s t u = V3.scale s (t u)
let mirror ax t u = V3.mirror ax (t u)
